### ISSUE TITLE
running tests fails

### ISSUE THREAD

**Issue by bigerl** [dice-group/rdf-parser#1]
see the log below:
```
/home/me/Code/pegtl_tnt_parser/cmake-build-debug/tests/bin/tests
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from TestParser
[ RUN      ] TestParser.ss
" hello  ""
1
0
[       OK ] TestParser.ss (0 ms)
[ RUN      ] TestParser.ssss
" hello  ""
1
0
[       OK ] TestParser.ssss (0 ms)
[ RUN      ] TestParser.sss
terminate called after throwing an instance of 'std::exception'
  what():  std::exception

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by bigerl** [comment]
The tests do not crash anymore.
But there are still tests failing: https://travis-ci.org/dice-group/rdf-parser/jobs/640058232?utm_medium=notification&utm_source=github_status

**Comment by Shaheen47** [comment]
yes, I know....there are still some tricky cases with parsing comments which I haven't fully solved yet...what do you suggest until I solved them .... to comment out the failing test cases or give the priority to solve those issues?

**Comment by bigerl** [comment]
Let's deactivate them instead of commenting them out. And please update the README with the limitations.

**Comment by Shaheen47** [comment]
OK done ... fixing the comment parsing is on  #7  .
