### ISSUE TITLE
code clean up

### ISSUE THREAD

**Issue by bigerl** [dice-group/rdf-parser#25]
- [x] eliminate virtual functions in Parsers where possible
- [x] eliminate unnecessary unique and shared pointers
- [x] update the readme
- [x] use https://conan.io/center/robin-hood-hashing map -> that map already uses a decent hash for strings
- [x] Make exceptions informative
- [x] use gtest like tentris https://github.com/dice-group/tentris/blob/260bffcff98d250512b2762d87e7b1ab01401181/tests/CMakeLists.txt#L4-L28

**Comment by Shaheen47** [comment]
2- mutex, condition_variable, and atomics have deleted copy constructor. Therefore, we have to pass them as pointers. Other cases have been resloved

**Comment by bigerl** [comment]
There might be a reason why the copy constructor is deleted. Is it safe to get a copy of a Parser and use both in parallel right now? 
Otherwise, a deleted copy constructor might be desired behavior or we would need to write a custom copy constructor.

**Comment by Shaheen47** [comment]
6- getting an error "CMake Error at /home/fakhr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.6682.181/bin/cmake/linux/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)"

**Comment by Shaheen47** [comment]
> There might be a reason why the copy constructor is deleted. Is it safe to get a copy of a Parser and use both in parallel right now?
> Otherwise, a deleted copy constructor might be desired behavior or we would need to write a custom copy constructor.

it looks c++17 and c++20 have some ref atomics and shared mutex, I will check them
